version: '3.8'

services:
  soccer_db:
    image: postgres:13
    container_name: soccer_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soccer_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  soccer-backend:
    build: .
    container_name: soccer_backend
    environment:
      DATABASE_URL: postgres://soccer_user:soccer_password@db:5432/soccer_db
    ports:
      - "5000:5000"
    depends_on:
      - soccer_db

volumes:
  db-data:
